CREATE TABLE game (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(60) NOT NULL,
  price INT NOT NULL,
  description VARCHAR(200) NOT NULL
);

INSERT INTO game
  (name, price, description)
VALUES
  ('Wingspan', '50', 'Attract a beautiful and diverse collection of birds to your wildlife reserve.'),
  ('Legends of Andor', '50', 'A group of heroes carefully executes the defense of a besieged kingdom.'),
  ('Azul', '50', 'Artfully embellish the walls of your palace by drafting the most beautiful tiles.'),
  ('Pandemic', '50', 'Your team of experts must prevent the world from succumbing to a viral pandemic.'),
  ('Clank!: A Deck-Building Adventure', '50', 'Claim your treasures but don''t attract the dragon in this deck-building dungeon race.'),
  ('The Crew: The Quest for Planet Nine', '50', 'Go on a planet-discovering space mission in this cooperative trick-taking game.'),
  ('Robinson Crusoe: Adventures on the Cursed Island', '50', 'Work together — with friends or with Friday — to survive on a deserted island.'),
  ('Detective: A Modern Crime Board Game', '50', 'Use modern tools and become Antares Detectives solving the most difficult cases.'),
  ('T.I.M.E. Stories', '50', 'Protect the world from paradoxes with your team of time-traveling agents.'),
  ('Above and Below', '50', 'Build your newly founded village above while exploring the caves and stories below.');