const mechanism = {
  deckbuild: 'Deckbuilding',
  coop: 'Cooperative',
  worker: 'Worker Placement',
  area: 'Area Movement',
  engine: 'Engine Building',
  dice: 'Dice Rolling',
  setColl: 'Set Collection',
  trick: 'Trick Winning',
  tile: 'Tile Placement',
  story: 'Storytelling',
  varPower: 'Variable Player Powers',
  action: 'Action Points',
};

const category = {
  adv: 'Adventure',
  abstract: 'Abstract',
  campaign: 'Campaign',
  dungeon: 'Dungeon Crawler',
  deduction: 'Deduction',
  mystery: 'Mystery/Murder',
  card: 'Card Game',
  scifi: 'Sceince Fiction',
  time: 'Time Travel',
  strategy: 'Strategy',
  fantasy: 'Fantasy',
  explore: 'Exploration',
};

export const games = [
  {
    id: 1,
    name: 'Wingspan',
    category: [category.strategy],
    mechanism: [
      mechanism.setColl,
      mechanism.engine,
      mechanism.dice,
      mechanism.action,
    ],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 2,
    name: 'Pandemic',
    category: [category.strategy],
    mechanism: [
      mechanism.coop,
      mechanism.varPower,
      mechanism.setColl,
      mechanism.action,
    ],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 3,
    name: 'Legends of Andor',
    category: [category.adv, category.campaign],
    mechanism: [mechanism.coop, mechanism.area, mechanism.action],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 4,
    name: 'Azul',
    category: [category.strategy, category.abstract],
    mechanism: [mechanism.setColl, mechanism.tile],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 5,
    name: 'Clank!',
    category: [category.adv, category.fantasy],
    mechanism: [mechanism.coop, mechanism.deckbuild],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 6,
    name: 'The Crew',
    category: [category.adv, category.scifi],
    mechanism: [mechanism.coop, mechanism.trick],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 7,
    name: 'Robinson Crusoe',
    category: [category.adv, category.explore],
    mechanism: [mechanism.coop, mechanism.dice, mechanism.tile],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 8,
    name: 'T.I.M.E. Stories',
    category: [category.adv, category.time, category.scifi],
    mechanism: [mechanism.coop, mechanism.story, mechanism.dice],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 9,
    name: 'Detective',
    category: [category.mystery],
    mechanism: [mechanism.coop, mechanism.story],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
  {
    id: 10,
    name: 'Above and Below',
    category: [category.adv, category.fantasy, category.explore],
    mechanism: [
      mechanism.worker,
      mechanism.dice,
      mechanism.setColl,
      mechanism.story,
    ],
    price: 50,
    desc: 'This is an awesome game that will make evenings with your friends and family fun and exciting.',
    playersMin: 2,
    playersMax: 4,
    timeMin: 60,
    timeMax: 120,
  },
];
